<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDna.Addin" Version="1.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="CopyFiles" AfterTargets="build">
    <ItemGroup>
      <SourceDll Include="$(OutputPath)runtimes\win-x64\native\*.dll"/>
    </ItemGroup>
    <Copy
      SourceFiles="@(SourceDll)"
      DestinationFolder="$(OutputPath)publish"/>
  </Target>
  
</Project>
