// <auto-generated />
using ExcelToSqlite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelToSqlite.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ExcelToSqlite.Models.Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TasksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("details");
                });

            modelBuilder.Entity("ExcelToSqlite.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("ExcelToSqlite.Models.Versions", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("内容")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("更新日")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Version");

                    b.ToTable("versions");
                });
#pragma warning restore 612, 618
        }
    }
}
